version: "3"

services:
  api:
    build:
      context: ./bookstore
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./bookstore:/app
    ports:
      - "8000:8000"

  client:
    build: ./Frontend
    ports:
      - 4200:4200
