# Generated by Django 5.1.1 on 2024-10-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('author', models.TextField(default='')),
                ('publisher', models.TextField(default='')),
                ('url', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('public_year', models.IntegerField(default=2000)),
                ('number', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('categories', models.ManyToManyField(to='book.category')),
            ],
        ),
    ]
