# Generated by Django 5.1.1 on 2024-09-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
