# Generated by Django 5.1.1 on 2024-09-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_public_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
