# Generated by Django 5.1.1 on 2024-09-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=2000),
        ),
    ]
