# Generated by Django 5.1.1 on 2024-10-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='fine',
            field=models.IntegerField(default=0),
        ),
    ]
