# Generated by Django 5.1.1 on 2024-10-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_record_fine'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
