# Generated by Django 5.1.1 on 2024-10-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_record_is_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='fine',
        ),
        migrations.RemoveField(
            model_name='record',
            name='is_complete',
        ),
    ]
